### PR TITLE
Adding functionality for clinical scans from LHSC

### PR DESCRIPTION
**Pull request by greydongilmore**

### CODE REVIEW

**Comment by greydongilmore** [comment]
Updates to **main.py**:
- added 3rd system arg for clinical scans (default is False) in **run()**
- added clinical sorting loop for DicomSorter, includes session number builder for scans in **main()**

Updates to **sort_rules()**:
- added definition, **sort_rule_clinical()**, for clinical scans

Added **clinical_helpers()**:
- provides functions for determining scan session numbers (as patients routinely receive scans on separate days) which are added to the tar filename (used later in heudiconv sort rule)

**Comment by akhanf** [comment]
@yinglilu are you able to review this pull request please? Thanks!

**Comment by akhanf** [comment]
also, @yinglilu do you know how to force circleci to perform a test on the pull request?

**Comment by yinglilu** [comment]
Hi Ali,

I have set CircleCI auto test:

[image: image.png]

Regards,

YingLi

**Comment by yinglilu** [comment]
Greydon will reopen PR

**Pull request closed without merging**
